const request = require('request');
const Web3 = require('web3');

abi = [{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"userAddress","type":"address"},{"indexed":false,"name":"tokenAddress","type":"address"},{"indexed":false,"name":"tokenAmount","type":"uint256"}],"name":"ChannelOpenned","type":"event"},{"constant":false,"inputs":[{"name":"_tokenAddress","type":"address"},{"name":"_tokenAmount","type":"uint256"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"openChannel","outputs":[{"name":"channelHash","type":"bytes32"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_channelHash","type":"bytes32"},{"name":"_refundAmount","type":"uint256"},{"name":"_channelCloseHash","type":"bytes32"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"closeChannel","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_channelHash","type":"bytes32"},{"name":"_refundAmount","type":"uint256"},{"name":"_channelCloseHash","type":"bytes32"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"voidChannel","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_channelHash","type":"bytes32"},{"name":"_refundAmount","type":"uint256"},{"name":"_channelCloseHash","type":"bytes32"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"finalizeVoidChannel","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_channelHash","type":"bytes32"},{"name":"_refundAmount","type":"uint256"},{"name":"_channelCloseHash","type":"bytes32"},{"name":"_v","type":"uint8"},{"name":"_r","type":"bytes32"},{"name":"_s","type":"bytes32"}],"name":"counterVoidChannel","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_channelHash","type":"bytes32"}],"name":"channel","outputs":[{"name":"","type":"address"},{"name":"","type":"uint256"},{"name":"","type":"uint8"},{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_tokenAddress","type":"address"},{"name":"_tokenAmount","type":"uint256"},{"name":"_account","type":"address"}],"name":"getChannelHash","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_channelHash","type":"bytes32"},{"name":"_refundAmount","type":"uint256"}],"name":"getChannelCloseHash","outputs":[{"name":"","type":"bytes32"}],"payable":false,"stateMutability":"view","type":"function"}]

let address = "0xb7d2795dc4824077407f18e964adabc0038149b2"

let web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));


state_channel = web3.eth.contract(abi).at(address);

state_channel.allEvents({fromBlock: 0, toBlock: "latest"}, (err, res) => {
  console.log(res);
})
